[arrangement]
name = "SMA_23bp"
kit = "SQK-NBD114-24"

mask1_front = "ATTGCTAAGGTTAA"
mask1_rear = "CAGCACCT"

barcode1_pattern = "SMA_23bp_NB%02i"

first_index = 4
last_index = 6

[scoring]
max_barcode_penalty = 11
min_barcode_penalty_dist = 3
min_separation_only_dist = 6
barcode_end_proximity = 75
flank_left_pad = 5
flank_right_pad = 10
front_barcode_window = 175
