experiment: 12282025_IF_DoubleBC_SMA_seq_no_trim
library_structure:
  description: 5'- PREFIX + ADAPTER + FLANK_F + BARCODE + FLANK_R + TARGET -3'
  elements:
    PREFIX:
      sequence: CCTGTACTTCGTT
      length: 13
      description: 13bp prefix before adapter
    ADAPTER:
      sequence: CAGTTACGTATTGCT
      length: 15
      description: 15bp Native Adapter end sequence
    FLANK_F:
      sequence: AAGGTTAA
      length: 8
      description: 8bp front flank (between adapter and barcode)
    FLANK_R:
      sequence: CAGCACCT
      length: 8
      description: 8bp rear flank (between barcode and target)
barcodes:
  BC02:
    sequence: ACAGACGACTACAAACGGAATCGA
    length: 24
    target: V0-4.2_forward
    target_description: V0-4.2 (forward orientation)
    size_range: &id001
    - 200
    - 260
  BC07:
    sequence: GGATTCATTCCCACGGTAACAC
    length: 22
    target: V0-4.2_reverse
    target_description: RC(V0-4.2) (reverse complement)
    size_range: *id001
  BC09:
    sequence: AACCAAGACTCGCTGTGCCTAGTT
    length: 24
    target: V0-4.4_forward
    target_description: V0-4.4 (forward orientation)
    size_range: &id002
    - 195
    - 255
  BC04:
    sequence: TAGCAAACACGATAGAATCCGAA
    length: 23
    target: V0-4.4_reverse
    target_description: RC(V0-4.4) (reverse complement)
    size_range: *id002
targets:
  V0-4.2_forward:
    description: V0-4.2 forward strand
    length: 161
    sequence: AGGATTTGCATAGATGGGTTTGGGAAAGGACATTCCAGGAGATCCCACTGTAAGAAGGGCCTGGAGGAGGAGGGGACATCTCAGACATGGTCGTGGGAGAGGTGTGCCCGGGTCAGGGGGCACCAGGAGAGGCCAAGGACTCTGTACCTCCTATCCACGTC
  V0-4.2_reverse:
    description: V0-4.2 reverse complement
    length: 161
    sequence: GACGTGGATAGGAGGTACAGAGTCCTTGGCCTCTCCTGGTGCCCCCTGACCCGGGCACACCTCTCCCACGACCATGTCTGAGATGTCCCCTCCTCCTCCAGGCCCTTCTTACAGTGGGATCTCCTGGAATGTCCTTTCCCAAACCCATCTATGCAAATCCT
  V0-4.4_forward:
    description: V0-4.4 forward strand
    length: 157
    sequence: TGGTGTAGGTGCTGAATGCTGTCCCCGTCCTCCTGCATATCCCAGCGCTGGCTGGCAAGGTCCTACGCTTCCAAAAGGCTTTCCTGACCCAGCTGGATGAGCTGCTAACTGAGCACAGGATGACCTGGGACCCAGCCCAGCCCCCCCGAGATCTGAC
  V0-4.4_reverse:
    description: V0-4.4 reverse complement
    length: 157
    sequence: GTCAGATCTCGGGGGGGCTGGGCTGGGTCCCAGGTCATCCTGTGCTCAGTTAGCAGCTCATCCAGCTGGGTCAGGAAAGCCTTTTGGAAGCGTAGGACCTTGCCAGCCAGCGCTGGGATATGCAGGAGGACGGGGACAGCATTCAGCACCTACACCA
full_references:
  BC02:
    length: 229
    sequence: CCTGTACTTCGTTCAGTTACGTATTGCTAAGGTTAAACAGACGACTACAAACGGAATCGACAGCACCTAGGATTTGCATAGATGGGTTTGGGAAAGGACATTCCAGGAGATCCCACTGTAAGAAGGGCCTGGAGGAGGAGGGGACATCTCAGACATGGTCGTGGGAGAGGTGTGCCCGGGTCAGGGGGCACCAGGAGAGGCCAAGGACTCTGTACCTCCTATCCACGTC
  BC07:
    length: 227
    sequence: CCTGTACTTCGTTCAGTTACGTATTGCTAAGGTTAAGGATTCATTCCCACGGTAACACCAGCACCTGACGTGGATAGGAGGTACAGAGTCCTTGGCCTCTCCTGGTGCCCCCTGACCCGGGCACACCTCTCCCACGACCATGTCTGAGATGTCCCCTCCTCCTCCAGGCCCTTCTTACAGTGGGATCTCCTGGAATGTCCTTTCCCAAACCCATCTATGCAAATCCT
  BC09:
    length: 225
    sequence: CCTGTACTTCGTTCAGTTACGTATTGCTAAGGTTAAAACCAAGACTCGCTGTGCCTAGTTCAGCACCTTGGTGTAGGTGCTGAATGCTGTCCCCGTCCTCCTGCATATCCCAGCGCTGGCTGGCAAGGTCCTACGCTTCCAAAAGGCTTTCCTGACCCAGCTGGATGAGCTGCTAACTGAGCACAGGATGACCTGGGACCCAGCCCAGCCCCCCCGAGATCTGAC
  BC04:
    length: 224
    sequence: CCTGTACTTCGTTCAGTTACGTATTGCTAAGGTTAATAGCAAACACGATAGAATCCGAACAGCACCTGTCAGATCTCGGGGGGGCTGGGCTGGGTCCCAGGTCATCCTGTGCTCAGTTAGCAGCTCATCCAGCTGGGTCAGGAAAGCCTTTTGGAAGCGTAGGACCTTGCCAGCCAGCGCTGGGATATGCAGGAGGACGGGGACAGCATTCAGCACCTACACCA
