# Great Lakes HPC Configuration
# Copy to ~/.ont-ecosystem/config/hpc.yaml

hpc:
  system: greatlakes
  scheduler: slurm
  
  partitions:
    gpu: [standard, gpu, spgpu, sigbio-a40]
    cpu: [standard, largemem]
  
  defaults:
    account: umms-athey
    time: "72:00:00"
    mem: 64G
    
  gpu_defaults:
    partition: spgpu
    gres: "gpu:1"
    cpus_per_task: 8
    
  reference_paths:
    - /nfs/turbo/umms-athey/references
    - /sw/references
    
  model_paths:
    - /nfs/turbo/umms-athey/dorado_models
    - /sw/dorado/models

  modules:
    - python/3.10
    - cuda/12.1
    - samtools/1.17
    - minimap2/2.26
