# SMA-seq Configuration for 11242025_IF_Part4_CIP_Treated_SMA_seq
experiment: "11242025_IF_Part4_CIP_Treated_SMA_seq"
demux_type: "standard_ont"
kit: "SQK-NBD114-24"

barcodes:
  barcode01:
    target: V0-4.1_forward
    alias: V04_1
    size_range: [150, 190]
  barcode02:
    target: V0-4.2_forward
    alias: V04_2
    size_range: [145, 185]
  barcode03:
    target: V0-4.3_forward
    alias: V04_3
    size_range: [168, 210]
  barcode04:
    target: V0-4.4_forward
    alias: V04_4
    size_range: [140, 180]
  barcode06:
    target: V0-4.1_reverse
    alias: V04_1_2
    size_range: [150, 190]
  barcode07:
    target: V0-4.2_reverse
    alias: V04_2_2
    size_range: [145, 185]
  barcode08:
    target: V0-4.3_reverse
    alias: V04_3_2
    size_range: [168, 210]
  barcode09:
    target: V0-4.4_reverse
    alias: V04_4_2
    size_range: [140, 180]
